services:
  food-vans-api:
    build:
      context: .
      dockerfile: src/OakTech.FoodVansApi/Dockerfile
    ports:
      - "8042:8080"

  slack-notifier:
    build:
      context: .
      dockerfile: src/OakTech.FoodVansSlackNotifier/Dockerfile
    ports:
      - "8043:8080"
    env_file:
      - .env